### ISSUE TITLE
Page: provide option to redefine or remove padding of main slot

### ISSUE THREAD

**Issue by aoloo** [kor-ui/kor#58]
Is it possible to modify a kor component? I want to use the `kor-page` component, but the component is adding unesseary styling that does not fit my use case  `slot:not([name]) { padding 16px}`. Can I remove this style without modifying the underlying component?

**Comment by eduferfer** [comment]
Hello @aoloo, for `kor-page` I could add an API to remove the margins, I think that would be helpful in other cases too.

In general, it is possible to modify the styles of shadow-root elements only by using JS, like: `myHTMLElement.shadowRoot.querySelector(slot:not([name])).style.padding = 0px;` but this should hopefully not be necessary since it becomes quite cumbersome.

**Comment by aoloo** [comment]
@eduferfer an api would be incredibly helpful. Thank you for your quick response.

**Comment by eduferfer** [comment]
@aoloo I will work on it tomorrow and publish a patch after that!

I haven't decided yet, but I am considering 2 options:

```html
<!-- through property -->
<kor-page padding="unset"></kor-page>
```

OR

```css
// through css variable 
kor-page {
  --padding: unset;
}
```

If you have any preference just let me know!

**Comment by aoloo** [comment]
Through property would make sense, since most of your components follow that pattern.

**Comment by eduferfer** [comment]
@aoloo version 1.5.2 is published, the property is called `padding` and takes any string that is compatible with the corresponding css rule. If you have any issue using it just let me know!

**Comment by aoloo** [comment]
@eduferfer thank you so much!!
